name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: "19 15 * * *"
  push:
    branches: ["main"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  preparation:
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.devcontainer-folders.outputs.folders }}
      commit_short_sha: ${{ steps.commit_short_sha.outputs.commit_short_sha }}
      repo: ${{ steps.lowercase-repo.outputs.repo }}
      image_timestamp: ${{ steps.timestamp.outputs.image_timestamp }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Get devcontainer folders
        id: devcontainer-folders
        run: echo "folders=$(ls src | jq -R -s -c 'split("\n")[:-1]')" | tee $GITHUB_OUTPUT
      - name: Set short git commit SHA
        id: commit_short_sha
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "commit_short_sha=$calculatedSha" | tee $GITHUB_OUTPUT      
      - name: Get lowercase repo name
        id: lowercase-repo
        run: echo "repo=${GITHUB_REPOSITORY@L}" | tee $GITHUB_OUTPUT

      # TODO: this should be replaced by regular calver versioning, but for now we need a unique tag 
      # to be able to push to ghcr without hitting "already exists" errors, because we want to keep the 
      # latest tag up to date for users who don't specify a version.
      - name: Create timestamp tag
        id: timestamp
        run: echo "image_timestamp=$(date -u +"%Y%m%dT%H%M%SZ")" | tee $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: preparation
    strategy:
      matrix:
        folder: ${{ fromJson(needs.preparation.outputs.folders) }}
        php_version: [8.5, 8.4, 8.3, 8.2]
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      # read image tag from subdirectory propery file if exists
      - name: Install Skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo
      - uses: xom9ikk/dotenv@v2.3.0
        with:
          path: "src/${{ matrix.folder }}"
          mode: ''
          load-mode: 'skip'
        env: 
          PHP_VERSION: ${{ matrix.php_version }}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set next image tag
        id: set-next-image-tag
        run: |
          last_imagecalvertag=$(skopeo list-tags --no-creds docker://ghcr.io/${IMAGE_NAME} | \
            jq -r --arg image_basetag "$image_basetag" '.Tags | sort_by(.) | [ .[] | select(.|startswith($image_basetag))]|[last][0]')
          last_imagecalver=${last_imagecalvertag##*-}
          next_imagecalver=$((last_imagecalver + 1))
        env: 
          IMAGE_NAME: ${{ env.REGISTRY }}/${{ needs.preparation.outputs.repo }}/${{ matrix.folder }}
          image_basetag: ${{ env.image_basetag }} # set in .env file in each subdirectory
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: src/${{ matrix.folder }}
          imageName: ${{ env.IMAGE_NAME }}
          imageTag: ${{ env.image_basetag }}
          #imageTag: ${{ env.image_basetag }}, ${{ env.image_basetag }}-${{ steps.set-next-image-tag.outputs.next_imagecalver }}
          cacheFrom: ${{ env.IMAGE_NAME }}:${{ env.image_basetag }}
          refFilterForPush: "refs/heads/main"
        env: 
          IMAGE_NAME: ${{ env.REGISTRY }}/${{ needs.preparation.outputs.repo }}/${{ matrix.folder }}
          IMAGE_TIMESTAMP: ${{ needs.preparation.outputs.image_timestamp }}
          COMMIT_SHORT_SHA: ${{ needs.preparation.outputs.commit_short_sha }}
          IMAGE_BASETAG: ${{ env.image_basetag }}
