# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Trivy Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '36 18 * * *'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: read

jobs:
  preparation:
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.devcontainer-folders.outputs.folders }}
      repo: ${{ steps.lowercase-repo.outputs.repo }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Get devcontainer folders
        id: devcontainer-folders
        run: echo "folders=$(ls src | jq -R -s -c 'split("\n")[:-1]')" | tee $GITHUB_OUTPUT
      - name: Get lowercase repo name
        id: lowercase-repo
        run: echo "repo=${GITHUB_REPOSITORY@L}" | tee $GITHUB_OUTPUT
  php-versions:
    runs-on: ubuntu-latest
    needs: preparation
    strategy:
      matrix:
        folder: ${{ fromJson(needs.preparation.outputs.folders) }}
    outputs:
      php_versions: ${{ steps.php-versions.outputs.php_versions }}
    steps:
      - name: Load php versions to process from config.json
        id: php-versions
        run: |
          php_versions=$(jq -r .ci.php_versions src/${{ matrix.folder }}/config.json)
          echo "php_versions=$php_versions" | tee $GITHUB_OUTPUT
  scan:
    permissions:
      #contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: ubuntu-latest
    needs: [preparation, php-versions]
    strategy:
      matrix:
        folder: ${{ fromJson(needs.preparation.outputs.folders) }}
        php_version: ${{ fromJson(needs.php-versions.outputs.php_versions) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: xom9ikk/dotenv@v2.4.0
        with:
          path: "src/${{ matrix.folder }}"
          mode: ''
          load-mode: 'skip'
        env: 
          PHP_VERSION: ${{ matrix.php_version }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: '${{ env.REGISTRY }}/${{ needs.preparation.outputs.repo }}/${{ matrix.folder }}:${{ env.TARGET_IMAGE_BASETAG }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          INPUT_LIMIT_SEVERITIES_FOR_SARIF: true
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
